name: hhc-shared-stack
services:
  hhc-api:
    build:
      context: ./services/api
      dockerfile: dockerfile
      target: development
    command: dlv debug /opt/go/src --headless --listen=:2345 --accept-multiclient
    container_name: hhc-api
    networks:
      - hhc-network
    restart: always
    environment:
      ADDRESS_PORT: 8080
    # ports:
    #   - "8080:8080"
    # - "2345:2345"
    volumes:
      - ./services/api/hhcshare:/opt/go/src:rw
    depends_on:
      hhc-db:
        condition: service_started
      hhc-migration:
        condition: service_completed_successfully
  # --------------------------------------
  hhc-db:
    platform: linux/amd64
    image: postgis/postgis:latest
    container_name: hhc-db
    networks:
      - hhc-network
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 5s
      timeout: 1s
      retries: 5
  # --------------------------------------
  hhc-migration:
    platform: linux/amd64
    build:
      context: ./services/migration
      args:
        - GEOM_VERSION=v0.1.1-alpha
    container_name: hhc-migration
    networks:
      - hhc-network
    restart: on-failure
    # entrypoint: ["sleep", "infinity"] # use this to jump into the container to check things
    environment:
      FLYWAY_DEFAULT_SCHEMA: hhc
      FLYWAY_USER: postgres
      FLYWAY_PASSWORD: postgres
      FLYWAY_URL: jdbc:postgresql://hhc-db:5432/postgres
      FLYWAY_VALIDATE_MIGRATION_NAMING: true
      PGHOST: hhc-db
      FLYWAY_PLACEHOLDERS_APP_PASSWORD: hhc_pass
      FLYWAY_PLACEHOLDERS_APP_USER: hhc_shared_user
    volumes:
      - ./services/migration/local:/flyway/sql/local:ro
    depends_on:
      hhc-db:
        condition: service_healthy
# --------------------------------------

networks:
  hhc-network:
    name: hhc-network
