name: hhc-shared-stack
services:
  hhc-db:
    platform: linux/amd64
    image: postgis/postgis:latest
    container_name: hhc-db
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
  # --------------------------------------
  hhc-migration:
    platform: linux/amd64
    container_name: hhc-migration
    build:
      context: ./services/migration
      args:
        - GEOM_VERSION=v0.1.1-alpha
    restart: on-failure
    # entrypoint: ["sleep", "infinity"] # use this to jump into the container to check things
    environment:
      FLYWAY_DEFAULT_SCHEMA: hhc
      FLYWAY_EDITION: community
      FLYWAY_LOCATIONS: filesystem:/flyway/sql
      FLYWAY_USER: postgres
      FLYWAY_PASSWORD: postgres
      FLYWAY_URL: jdbc:postgresql://hhc-db:5432/postgres
      FLYWAY_VALIDATE_MIGRATION_NAMING: true
      FLYWAY_DB_HOST: hhc-db
      FLYWAY_PLACEHOLDERS_APP_PASSWORD: app_pass
      FLYWAY_PLACEHOLDERS_GIS_PASSWORD: gis_pass
    depends_on:
      - hhc-db
    volumes:
      - ./services/migration/local:/flyway/sql/local:ro
# --------------------------------------

networks:
  hhc_network:
