services:
  minio:
    image: minio/minio
    container_name: minio
    networks:
      - hhc-network
    environment:
      MINIO_ROOT_USER: AKIAIOSFODNN7EXAMPLE
      MINIO_ROOT_PASSWORD: wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY
    command: server /data --console-address ":9001"
    ports:
      - "9000-9001:9000-9001"
  # --------------------------------------
  minio-init:
    image: minio/mc
    container_name: minio-init
    networks:
      - hhc-network
    entrypoint:
      - /bin/sh
      - -c
      - |
        echo 'sleep for 5sec'
        sleep 5
        /usr/bin/mc alias set minio http://minio:9000 AKIAIOSFODNN7EXAMPLE wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY
        /usr/bin/mc mb --ignore-existing minio/hhc-shared-dev
        /usr/bin/mc anonymous set public minio/hhc-shared-dev
        /usr/bin/mc cp --recursive /media/ minio/hhc-shared-dev/
    depends_on:
      minio:
        condition: service_started
    volumes:
      - ./_media:/media

# --------------------------------------
networks:
  hhc-network:
    external: true
