#This is a basic workflow to help you get started with Actions
name: Build/Push DB Migration to Dev, Test, or Prod

# Controls when the action will run. Invokes the workflow on push events but only for the main branch
on:
  push:
    branches: [cwbi-dev, cwbi-test] # cwbi-prod
    paths:
      - .github/workflows/cwbi-build-push-migration.yml
      - "services/migration/**"
  schedule:
    - cron: "3 11 * * 2" # Every Tuesday morning at 11:03 UTC (high loads are on the hour)
  # Allow the workflow to be triggered manually from the GitHub UI
  workflow_dispatch:

env:
  AWS_REGION: us-gov-west-1 #Change to reflect your Region
  PATH_TO_DOCKERFILE: services/migration
  CWBI_DEV_ROLE: arn:aws-us-gov:iam::718787032875:role/github-actions-ecr-hhc-shared
  CWBI_TEST_ROLE: arn:aws-us-gov:iam::276847049069:role/github-actions-ecr-hhc-shared
  CWBI_PROD_ROLE: arn:aws-us-gov:iam::648157167324:role/github-actions-ecr-hhc-shared

# Permission can be added at job level or workflow level
permissions:
  id-token: write # This is required for requesting the JWT
  contents: read # This is required for actions/checkout

jobs:
  #~*~*~*~*~*~*~*~*~*~*~*~*~*~*~*~*~*~*~*~*~*~*~*~*~*~*~*~*~*~*~*~*~*~*~*~
  build-push-dev:
    if: >-
      github.event_name == 'schedule' ||
      github.ref == 'refs/heads/cwbi-dev'
    runs-on: ubuntu-latest
    env:
      ECR_REPOSITORY: hhc-shared-migration
      IMAGE_TAG: dev
    steps:
      - uses: actions/checkout@v4
        with:
          ref: cwbi-dev
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ${{ env.AWS_REGION }}
          role-to-assume: ${{ env.CWBI_DEV_ROLE }}
          output-credentials: true

      # Hello from AWS: WhoAmI
      - name: Sts GetCallerIdentity
        run: aws sts get-caller-identity

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2
        with:
          mask-password: "true"

      - name: Build Image; Push to ECR
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        run: |
          docker build --push \
          --tag $ECR_REGISTRY/${{ env.ECR_REPOSITORY }}:latest \
          --tag $ECR_REGISTRY/${{ env.ECR_REPOSITORY }}:${{ env.IMAGE_TAG }} \
          ${{ env.PATH_TO_DOCKERFILE }}

      - name: ECR Logout
        if: always()
        run: docker logout ${{ steps.login-ecr.outputs.registry }}

  #~*~*~*~*~*~*~*~*~*~*~*~*~*~*~*~*~*~*~*~*~*~*~*~*~*~*~*~*~*~*~*~*~*~*~*~
  build-push-test:
    if: >-
      github.event_name == 'schedule' ||
      github.ref == 'refs/heads/cwbi-test'
    runs-on: ubuntu-latest
    env:
      ECR_REPOSITORY: hhc-shared-migration
      IMAGE_TAG: test
    steps:
      - uses: actions/checkout@v4
        with:
          ref: cwbi-test
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ${{ env.AWS_REGION }}
          role-to-assume: ${{ env.CWBI_TEST_ROLE }}
          output-credentials: true

      # Hello from AWS: WhoAmI
      - name: Sts GetCallerIdentity
        run: aws sts get-caller-identity

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2
        with:
          mask-password: "true"

      - name: Build Image; Push to ECR
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        run: |
          docker build --push \
          --tag $ECR_REGISTRY/${{ env.ECR_REPOSITORY }}:latest \
          --tag $ECR_REGISTRY/${{ env.ECR_REPOSITORY }}:${{ env.IMAGE_TAG }} \
          ${{ env.PATH_TO_DOCKERFILE }}

      - name: ECR Logout
        if: always()
        run: docker logout ${{ steps.login-ecr.outputs.registry }}

  #~*~*~*~*~*~*~*~*~*~*~*~*~*~*~*~*~*~*~*~*~*~*~*~*~*~*~*~*~*~*~*~*~*~*~*~
  # build-push-prod:
  #   if: >-
  #     github.event_name == 'schedule' ||
  #     github.ref == 'refs/heads/cwbi-prod'
  #   runs-on: ubuntu-latest
  #   env:
  #     ECR_REPOSITORY: hhc-shared-migration
  #     IMAGE_TAG: prod
  #   steps:
  #     - uses: actions/checkout@v4
  #       with:
  #         ref: cwbi-prod
  #     - name: Configure AWS Credentials
  #       uses: aws-actions/configure-aws-credentials@v4
  #       with:
  #         aws-region: ${{ env.AWS_REGION }}
  #         role-to-assume: ${{ env.CWBI_PROD_ROLE }}
  #         output-credentials: true

  #     # Hello from AWS: WhoAmI
  #     - name: Sts GetCallerIdentity
  #       run: aws sts get-caller-identity

  #     - name: Login to Amazon ECR
  #       id: login-ecr
  #       uses: aws-actions/amazon-ecr-login@v2
  #       with:
  #         mask-password: "true"

  #     - name: Build Image; Push to ECR
  #       env:
  #         ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
  #       run: |
  #         docker build --push \
  #         --tag $ECR_REGISTRY/${{ env.ECR_REPOSITORY }}:latest \
  #         --tag $ECR_REGISTRY/${{ env.ECR_REPOSITORY }}:${{ env.IMAGE_TAG }} \
  #         ${{ env.PATH_TO_DOCKERFILE }}

  #     - name: ECR Logout
  #       if: always()
  #       run: docker logout ${{ steps.login-ecr.outputs.registry }}
